In [18]:
import numpy as np
import pandas as pd

In [19]:
#1. Create a series of three different colors 

colors = ["Red","Green","Black"]

color_series = pd.Series(colors)

print(color_series)

0      Red
1    Green
2    Black
dtype: object

In [20]:
#2.View the series of different colors 

color_series

0      Red
1    Green
2    Black
dtype: object

In [21]:
#3.Create a series of three different car types and view it 

cars = ["Sedan","SUV","Hatchback"]

cars_series = pd.Series(cars)

print(cars_series)

0        Sedan
1          SUV
2    Hatchback
dtype: object

In [22]:
#4.Combine the Series of cars and colors into a Data Frame 

data = {"colors":color_series,"cars":cars_series}

df =pd.DataFrame(data)
df

  colors       cars
0    Red      Sedan
1  Green        SUV
2  Black  Hatchback

In [23]:
#5.  Find the different datatypes of the car data Data Frame 




car_sale = {
    'Make': ['Toyota','Honda','Ford','Tesla','BMW','Hyundai','Kia','Maruti','Mahindra','AUdi','Mercedes','Jeep'],
    'Car Model': [
        'Toyota Corolla', 'Honda Civic', 'Ford Mustang', 'Tesla Model 3', 'BMW X5',
        'Hyundai Elantra', 'Kia Seltos', 'Maruti Swift', 'Mahindra Thar', 'Audi A4',
        'Mercedes C-Class', 'Jeep Compass'
    ],
    'Year': [2020, 2019, 2021, 2022, 2021, 2020, 2022, 2021, 2022, 2020, 2021, 2019],
    'Door':[4,4,2,4,5,4,4,4,5,2,2,4],
    'Price ($)': [20000, 18000, 35000, 45000, 60000, 17000, 25000, 12000, 27000, 40000, 55000, 30000],
    'Units Sold': [150, 120, 75, 200, 50, 180, 160, 300, 90, 60, 55, 100],
    'Region': ['North', 'East', 'West', 'South', 'North', 'East', 'West', 'South', 'North', 'East', 'West', 'South']
}


df = pd.DataFrame(car_sale)

print(df)

        Make         Car Model  Year  Door  Price ($)  Units Sold Region
0     Toyota    Toyota Corolla  2020     4      20000         150  North
1      Honda       Honda Civic  2019     4      18000         120   East
2       Ford      Ford Mustang  2021     2      35000          75   West
3      Tesla     Tesla Model 3  2022     4      45000         200  South
4        BMW            BMW X5  2021     5      60000          50  North
5    Hyundai   Hyundai Elantra  2020     4      17000         180   East
6        Kia        Kia Seltos  2022     4      25000         160   West
7     Maruti      Maruti Swift  2021     4      12000         300  South
8   Mahindra     Mahindra Thar  2022     5      27000          90  North
9       AUdi           Audi A4  2020     2      40000          60   East
10  Mercedes  Mercedes C-Class  2021     2      55000          55   West
11      Jeep      Jeep Compass  2019     4      30000         100  South

In [24]:
#6.Describe your current car sales Data Frame using describe () 

print(df.describe())

              Year       Door     Price ($)  Units Sold
count    12.000000  12.000000     12.000000   12.000000
mean   2020.666667   3.666667  32000.000000  128.333333
std       1.073087   1.073087  15368.208034   73.926663
min    2019.000000   2.000000  12000.000000   50.000000
25%    2020.000000   3.500000  19500.000000   71.250000
50%    2021.000000   4.000000  28500.000000  110.000000
75%    2021.250000   4.000000  41250.000000  165.000000
max    2022.000000   5.000000  60000.000000  300.000000

In [25]:
#7.Get information about your Data Frame using info () 

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Make        12 non-null     object
 1   Car Model   12 non-null     object
 2   Year        12 non-null     int64
 3   Door        12 non-null     int64
 4   Price ($)   12 non-null     int64
 5   Units Sold  12 non-null     int64
 6   Region      12 non-null     object
dtypes: int64(4), object(3)
memory usage: 804.0+ bytes
None

In [26]:
#8.Create a Series of different numbers and find the mean of them 

num = [10,20,15,14,21,28,50,36]

n_series = pd.Series(num)

print("Mean of the series is :",n_series.mean())

Mean of the series is : 24.25

In [27]:
#9.Create a Series of different numbers and find the sum of them

series = pd.Series([10,25.5,56,60,74,85.3,98,144,75])

print("Sum of series is:",series.sum())

Sum of series is: 627.8

In [28]:
#10.List out all the column names of the car sales Data Frame 

print("Colomn names in dataframe are:",df.columns.to_list())

Colomn names in dataframe are: ['Make', 'Car Model', 'Year', 'Door', 'Price ($)', 'Units Sold', 'Region']

In [29]:
#11.Find the length of the car sales Data Frame 

print("Length of Dataframe is :",len(df))

Length of Dataframe is : 12

In [30]:
#12.Show the first 5 rows of the car sales Data Frame 

df.head(5)

     Make       Car Model  Year  Door  Price ($)  Units Sold Region
0  Toyota  Toyota Corolla  2020     4      20000         150  North
1   Honda     Honda Civic  2019     4      18000         120   East
2    Ford    Ford Mustang  2021     2      35000          75   West
3   Tesla   Tesla Model 3  2022     4      45000         200  South
4     BMW          BMW X5  2021     5      60000          50  North

In [31]:
#13.Show the first 7 rows of the car sales Data Frame 

df.head(7)

      Make        Car Model  Year  Door  Price ($)  Units Sold Region
0   Toyota   Toyota Corolla  2020     4      20000         150  North
1    Honda      Honda Civic  2019     4      18000         120   East
2     Ford     Ford Mustang  2021     2      35000          75   West
3    Tesla    Tesla Model 3  2022     4      45000         200  South
4      BMW           BMW X5  2021     5      60000          50  North
5  Hyundai  Hyundai Elantra  2020     4      17000         180   East
6      Kia       Kia Seltos  2022     4      25000         160   West

In [32]:
#14.Show the bottom 5 rows of the car sales Data Frame

df.tail(5)

        Make         Car Model  Year  Door  Price ($)  Units Sold Region
7     Maruti      Maruti Swift  2021     4      12000         300  South
8   Mahindra     Mahindra Thar  2022     5      27000          90  North
9       AUdi           Audi A4  2020     2      40000          60   East
10  Mercedes  Mercedes C-Class  2021     2      55000          55   West
11      Jeep      Jeep Compass  2019     4      30000         100  South

In [33]:
#15.Use. loc to select the row at index 3 of the car sales Data Frame 

df.loc[3]

Make                  Tesla
Car Model     Tesla Model 3
Year                   2022
Door                      4
Price ($)             45000
Units Sold              200
Region                South
Name: 3, dtype: object

In [34]:
#16.Use. iloc to select the row at position 3 of the car sales Data Frame 

df.iloc[3]

Make                  Tesla
Car Model     Tesla Model 3
Year                   2022
Door                      4
Price ($)             45000
Units Sold              200
Region                South
Name: 3, dtype: object

In [36]:
#17. Create a crosstab of the Make and Doors columns.

pd.crosstab(df["Make"],df["Door"])

Door      2  4  5
Make
AUdi      1  0  0
BMW       0  0  1
Ford      1  0  0
Honda     0  1  0
Hyundai   0  1  0
Jeep      0  1  0
Kia       0  1  0
Mahindra  0  0  1
Maruti    0  1  0
Mercedes  1  0  0
Tesla     0  1  0
Toyota    0  1  0